name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  # ビルドとテストなどを検証する
  build_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable
      # ビルドチェック
      - run: yarn build
      # フォーマットチェック
      - run: yarn lint
      # テスト実施
      - run: yarn test

  # タグバージョンを検証する
  tag_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Tag check
        run: |
          # タグ情報のみfetch
          git fetch --tags
          git tag -n
          # package.jsonからバージョン取得
          export TAG_VERSION=v$(node -e "console.log(require('./package.json').version)")
          echo "this branch version is $TAG_VERSION"
          # 取得したバージョンでタグ生成を試みてエラーだったらバージョン変更なし
          git tag $TAG_VERSION
